// ============================================================================
// File: include/apps/cpu_tlp_shared_cache/simulation/processor/pe/ControlUnit.h
// ============================================================================

#pragma once

/**
 * @file ControlUnit.h
 * @brief Control unit for PE instruction decoding.
 *
 * Decodes opcode to generate control signals for pipeline stages.
 *
 * @note Follows:
 *   - SRP: Only generates control signals from opcode
 *   - Stateless: Pure decoding function
 */

#include <cstdint>

namespace cpu_tlp {

    /**
     * @struct ControlSignals
     * @brief Control signals generated by control unit.
     */
    struct ControlSignals {
        uint8_t RegWrite_D;     ///< Register write enable
        uint8_t MemOp_D;        ///< Memory operation flag
        uint8_t C_WE_D;         ///< Cache write enable
        uint8_t C_REQUEST_D;    ///< Cache request flag
        uint8_t C_ISB_D;        ///< Instruction synchronization barrier
        uint8_t PCSrc_D;        ///< PC source selector
        uint8_t FlagsUpd_D;     ///< Flags update enable
        uint8_t ALUControl_D;   ///< ALU operation code
        uint8_t BranchOp_D;     ///< Branch operation type
        uint8_t BranchE;        ///< Branch in execute flag
        uint8_t ImmOp;          ///< Immediate operand flag
        uint8_t DataType;       ///< Data type (0=int, 1=float)
    };

    /**
     * @class ControlUnit
     * @brief Stateless instruction decoder.
     */
    class ControlUnit {
    public:
        /**
         * @brief Decodes opcode to control signals.
         * @param opcode 8-bit opcode.
         * @return Control signals structure.
         */
        ControlSignals decode(uint8_t opcode) const;
    };

} // namespace cpu_tlp